### ISSUE TITLE
Weird grainy world issue!

### ISSUE THREAD

**Issue by SamhitApple** [MrScautHD/Space-Bosstools-1.16.4#11]
When I play with this mod, for some reason, the world looks grainy and noisy!  For better understanding, take a look at the video below: 
**Video:**
https://youtu.be/fS1uwSmJo7Q
**Log File:**
https://pastebin.com/MQexfyah
_(I had to make it an unlisted video and put it on YT since video files exceeding 10 MB can't be posted on Github!)_

**Comment by Scout24HD** [comment]
i know what you mean but this is not Space-Bosstools this make this world grainy(test it with only space-bosstools)

**Comment by SamhitApple** [comment]
Is it a clash between Optifine and this mod? Because when I tried removing this mod, that grainy thing goes away!

**Comment by Scout24HD** [comment]
> 
> 
> Is it a clash between Optifine and this mod? Because when I tried removing this mod, that grainy thing goes away!

Can you test it pls only with Space-Bosstools and not with other mods (other mods can get broken by Space-bosstools... and then make this mods the grainy)

**Comment by SamhitApple** [comment]
I tested this mod with only Optifine installed, there was no such grainy issue! Must be an incompatibility with another mod.

**Comment by loli252** [comment]
i think its is not a Space-Bosstools Problem a other mod is incompatibility with it. (in the log only other mods make Errors)
