### ISSUE TITLE
missing tag support

### ISSUE THREAD

**Issue by ModernGamingWorld** [MrScautHD/Space-Bosstools-1.16.4#12]
Iron plate is not using the forge:plates/iron to allow this mods recipes and such to use other mods Iron Plates
Steel Ingot is not using the forge:ingots/steel to allow this mods recipes and such to use other mods Steel
Iron Stick is not using the forge:rods/iron
Steel Block is not using forge:storage_blocks/steel

**Comment by benbenlaw** [comment]
need this support

**Comment by MrScautHD** [comment]
added in 4.3
