### ISSUE TITLE
server crash on load up[1.16.4-3.9]

### ISSUE THREAD

**Issue by SDUBZ** [MrScautHD/Space-Bosstools-1.16.4#13]
forge: 1.16.4-35.1.29
boss tools: 1.16.4-3.9

crash report: 
[crash-2021-01-14_16.19.44-fml.txt](https://github.com/MrScautHD/Space-Bosstools-1.16.4/files/5815735/crash-2021-01-14_16.19.44-fml.txt)

logs:
[latest.log](https://github.com/MrScautHD/Space-Bosstools-1.16.4/files/5815736/latest.log)
[debug.log](https://github.com/MrScautHD/Space-Bosstools-1.16.4/files/5815737/debug.log)

**Comment by MrScautHD** [comment]
Thx for the Bug Report is in the next Version fixed :)
