### ISSUE TITLE
Server crashing upon placing rocket on launchpad

### ISSUE THREAD

**Issue by Weirddudewastaken** [MrScautHD/Space-Bosstools-1.16.4#14]
[Crash report.txt](https://github.com/MrScautHD/Space-Bosstools-1.16.4/files/5931631/Crash.report.txt)
these are the logs after I placed the rocket on the launchpad
I have no idea what is wrong but it definitely was something with space Bosstools

**Comment by MrScautHD** [comment]
this is only a forge mod not a forge + craftbukket mod:
 [net.minecraftforge.fml.loading.ModJarURLHandler/CORE]: Loading modjar URL modjar://forge/org/bukkit/craftbukkit/v1_16_R3/inventory/CraftMetaEnchantedBook$1.class got resource org/bukkit/craftbukkit/v1_16_R3/inventory/CraftMetaEnchantedBook$1.class true
