### ISSUE TITLE
Overwrites byg Biomes

### ISSUE THREAD

**Issue by SkyzerFlyzer** [MrScautHD/Space-Bosstools-1.16.4#7]
The mod will overwrite byg biomes when installed on a world that has already generated the map

The byg alps biome becomes lunarorbit biome

Steps to reproduce
1 Install byg (https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go)
2 Generate world and locate the alps biome
3 Install Space-Bosstools 
4 The biome will have changed

**Comment by MrScautHD** [comment]
can you send me any example?
logs...
and what is the lunaorbit biome? xD

**Comment by MrScautHD** [comment]
This is a Problem with Minecraft Self i can't fix this.
