### ISSUE TITLE
Mod removal bricks dimensions

### ISSUE THREAD

**Issue by SkyzerFlyzer** [MrScautHD/Space-Bosstools-1.16.4#8]
When removing the mod any dimension that you have been to will be unlinked

This means no nether and no end

Steps to reproduce
1 Generate world with Space-Bosstools installed
2 Go to the nether and come back to the overworld
3 Remove Space-Bosstools
4 Reload the world and try to go into the nether

**Comment by MrScautHD** [comment]
I know that but I don't know why this error exists because the mod file doesn't change anything (its is removed)
