### ISSUE TITLE
Updating Terrain Gen & Ore Spawning

### ISSUE THREAD

**Issue by SamhitApple** [MrScautHD/Space-Bosstools-1.16.4#9]
-The planets are quite nice, but some terrain generation changes would be nice! Like it's almost flat! On mars for instance, hills here and there could be added.
-The ores spawning on the moon and mars are actually VERY rare and quite deep in caves very difficult to just stumble upon! It would be nice if the height at which these spawn is increased and a few patches of these ores actually spawn on the surface too!

**Comment by MrScautHD** [comment]
is added in 3.7
